DROP TABLE IF EXISTS thing1;
DROP TABLE IF EXISTS thing2;

CREATE TABLE thing1
(
  id1 INTEGER,
  PRIMARY KEY(id1)
) ENGINE=INNODB;

CREATE TABLE thing2
(
  id2 INTEGER,

   PRIMARY KEY(id2),
   FOREIGN KEY (id2) REFERENCES thing1(id1) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB;